name: reproducible-analysis

services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mor-interval
    ports:
      - "8787:8787"
    environment:
      DISABLE_AUTH: "true"
    restart: unless-stopped